library(ggplot2)
hoge <- read.csv("test.csv", header = F)
ggplot(hoge, aes(y=hoge$data, x=hoge$time)) + geom_point() + xlab("unix time") + ylab("type of data")

library(grid)
hoge1 <- read.csv("module-client_src_test_java_org_apache_http_conn_TestScheme_java__4.csv", header = F)
a <- ggplot(hoge1, aes(y=hoge1$V5, x=hoge1$V2)) + geom_point() + xlab("unix time") + ylab("type of data") + ggtitle("example 1")
hoge2 <- read.csv("httpclient-cache_src_test_java_org_apache_http_impl_client_cache_ehcache_TestEhcacheProtcolRequirements_java__3.csv", header = F)
b <- ggplot(hoge2, aes(y=hoge2$V5, x=hoge2$V2)) + geom_point() + xlab("unix time") + ylab("type of data") + ggtitle("example 2")
hoge3 <- read.csv("module-client_src_test_java_org_apache_http_conn_TestScheme_java__1.csv", header = F)
c <- ggplot(hoge3, aes(y=hoge3$V5, x=hoge3$V2)) + geom_point() + xlab("unix time") + ylab("type of data") + ggtitle("example 3")
grid.newpage()
pushViewport(viewport(layout=grid.layout(3,1)))
print(a, vp=viewport(layout.pos.row=1, layout.pos.col=1))
print(b, vp=viewport(layout.pos.row=2, layout.pos.col=1))
print(c, vp=viewport(layout.pos.row=3, layout.pos.col=1))
dev.copy2eps(file="../../kousatsu2.eps")
